# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Github Specifics: https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll

# All default settings from https://jekyllrb.com/docs/configuration/default/
# and changed when needed

# Be aware of directory paths!
# In general, make directory path values in configuration keys like plugins_dir
# relative to the current working directory, not the site source. The sass
# configuration key is an exception, where values must be relative to the site
# source.

# More
#  http://kramdown.gettalong.org/quickref.html
#  http://kramdown.gettalong.org/options.html
#  https://stackoverflow.com/questions/6615415/add-syntax-highlighting-to-gh-pages
# https://github.com/jekyll/jekyll/pull/4090
# Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html


# Where things are
#-----------------
#source              : .
#destination         : ./_site
#collections_dir     : .
#plugins_dir         : _plugins # takes an array of strings and loads plugins in that order
#layouts_dir         : _layouts
#data_dir            : _data
#includes_dir        : _includes
#sass:
#  sass_dir: _sass
#collections:
#posts:
#  output          : true


# Handling Reading
#-----------------
safe                : true # (no caching)      # false
#include             : [".htaccess"]
#exclude             : ["Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/"]
#keep_files          : [".git", ".svn"]
#encoding            : "utf-8"
#markdown_ext        : "markdown,mkdown,mkdn,mkd,md"
#strict_front_matter : true      # false

# Filtering Content
#------------------
#show_drafts         : null
#limit_posts         : 0
#future              : false
#unpublished         : false

# Plugins
#--------
#whitelist           : []
#remote_theme: pages-themes/tactile@v0.2.0
plugins:
#  - jekyll-remote-theme
  - jekyll-feed
  - kramdown
#  - kramdown-plantuml

# Conversion
#-----------
markdown            : kramdown
highlighter         : rouge
#lsi                 : false
#excerpt_separator   : "\n\n"
#incremental         : false

# https://github.com/benbalter/jekyll-optional-front-matter
optional_front_matter:
  remove_originals: true
  enabled: true

# Serving
#--------
#detach              : false
#port                : 4000
#host                : 127.0.0.1
#show_dir_listing    : false
#url: "https://martimm.github.io"
baseurl: ""


#theme: jekyll-theme-tactile
title: MARTIMM's
description: About all my projects

email: mt1957@gmail.com
github_username:  MARTIMM
github: [metadata]

#liquid:
#  error_mode        : warn
#  strict_filters    : false
#  strict_variables  : false

# Markdown Processors
#--------------------
kramdown:
#  auto_ids          : true
#  entity_output     : as_char
#  toc_levels        : [1, 2, 3, 4, 5, 6]
#  smart_quotes      : lsquo,rsquo,ldquo,rdquo
  input             : GFM
#  hard_wrap         : false
#  footnote_nr       : 1
#  show_warnings     : false


# Outputting
#-----------
#permalink           : date
#paginate_path       : /page:num
#timezone            : null

#quiet               : false
#verbose             : true      # false

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - bin
  - doc
  - docs
  - lib
  - Old
  - vendor
  - xt
  - .directory
  - .bundle
  - .git
  - .github
  - .jekyll-cache

# Not excluded;
#  - label      # directory raku icon and license labels

#defaults:
#  -
#    scope:
#      path: "content-docs/reference/Gtk3"
#    values:
#      layout: reference-page
#      title: References to the Gtk3 package modules
#      nav_menu: references-nav
#      sidebar_menu: references-gtk3-sidebar

defaults:

    #--[API 1]------------------------------------------------------------------
  - scope:
      path: content-docs/api1/reference/Gtk3
      type: pages
    values:
      layout: reference-page
      part-title: Gtk3 Api1 reference
      nav_menu: api1ref-nav
      sidebar_menu: api1-ref-gtk3-sidebar

  - scope:
      path: content-docs/api1/reference/Gdk3
      type: pages
    values:
      layout: reference-page
      part-title: Gdk3 Api1 reference
      nav_menu: api1ref-nav
      sidebar_menu: api1-ref-gdk3-sidebar

  - scope:
      path: content-docs/api1/reference/Gio
      type: pages
    values:
      layout: reference-page
      part-title: Gio Api1 reference
      nav_menu: api1ref-nav
      sidebar_menu: api1-ref-gio-sidebar

  - scope:
      path: content-docs/api1/reference/Glib
      type: pages
    values:
      layout: reference-page
      part-title: Glib Api1 reference
      nav_menu: api1ref-nav
      sidebar_menu: api1-ref-glib-sidebar

  - scope:
      path: content-docs/api1/reference/GObject
      type: pages
    values:
      layout: reference-page
      part-title: GObject Api1 reference
      nav_menu: api1ref-nav
      sidebar_menu: api1-ref-gobject-sidebar

    #--[API 2]------------------------------------------------------------------
  - scope:
      path: content-docs/api2/reference/Gtk4
      type: pages
    values:
      layout: reference-page
      part-title: Gtk4 Api2 reference
      nav_menu: api2ref-nav
      sidebar_menu: api2-ref-gtk4-sidebar

  - scope:
      path: content-docs/api2/reference/Gsk4
      type: pages
    values:
      layout: reference-page
      part-title: Gsk4 Api2 reference
      nav_menu: api2ref-nav
      sidebar_menu: api2-ref-gsk4-sidebar

  - scope:
      path: content-docs/api2/reference/Graphene
      type: pages
    values:
      layout: reference-page
      part-title: Graphene Api2 reference
      nav_menu: api2ref-nav
      sidebar_menu: api2-ref-graphene-sidebar

  - scope:
      path: content-docs/api2/reference/Gdk4
      type: pages
    values:
      layout: reference-page
      part-title: Gdk 4 Api2 reference
      nav_menu: api2ref-nav
      sidebar_menu: api2-ref-gdk4-sidebar

  - scope:
      path: content-docs/api2/reference/Gio
      type: pages
    values:
      layout: reference-page
      part-title: Gio Api2 reference
      nav_menu: api2ref-nav
      sidebar_menu: api2-ref-gio-sidebar

  - scope:
      path: content-docs/api2/reference/Pango
      type: pages
    values:
      layout: reference-page
      part-title: Pango Api2 reference
      nav_menu: api2ref-nav
      sidebar_menu: api2-ref-pango-sidebar

    #--[XMas stories]-----------------------------------------------------------
  - scope:
      path: content-docs/XMas
      type: pages
    values:
      layout: xmas-page
      part-title: XMas Story
      nav_menu: xmas-nav
#      sidebar_menu: api2-ref-gtk4-sidebar
