highlighter: pygments
github: [Repository metadata]

# Predefined Global, config or frontmatter
#
# layout        _layouts
# permalink     /year/month/day/title.html
# published     true/false
# category      
# categories
# tags

# date          overides post date of filename

# Different types: pages, posts, drafts.Create new ones with collections
#
collections:
  - MongoDB:
      output: true

# Default settings
#
defaults:
  - scope:
     path: Blog
     type: posts
    values:
     permalink: /:year/:month-:day-:title.html
     author: Marcel Timmerman
     layout: post

  - scope:
     path: Projects/MongoDB
     type: MongoDB
    values:
     author: Marcel Timmerman
     layout: default
